### ISSUE TITLE
Problems accessing hdfs from outside container

### ISSUE THREAD

**Issue by mooselinf** [caioquirino/docker-cloudera-quickstart#13]
Hiya

This is a great container but I am having problems with accessing the hdfs folders from outside the container - I am getting a connection refused exception - specifically when coupled with apache camel. Is it something I have done or a problem with the container. I can access the file system from hue but not from outside!!

Any ideas?

Scott

**Comment by caioquirino** [comment]
Did you expose the HDFS port?
Example: docker ..... -p 50075:50075

**Comment by seglo** [comment]
I'm having the same problem.  I don't have much experience configuring HDFS. I'm running the latest vesion of your docker image.  When I attach to the container console I can list the contents of HDFS fine.

``` bash
root@05478c6b64f9:/# hadoop fs -ls hdfs://localhost:8020/                                                                                                                 
Found 7 items
drwxr-xr-x   - hdh   supergroup          0 2015-11-03 11:07 hdfs://localhost:8020/HDH
drwxrwxrwx   - hdfs  supergroup          0 2015-11-03 11:04 hdfs://localhost:8020/benchmarks
drwxr-xr-x   - hbase supergroup          0 2015-11-03 11:04 hdfs://localhost:8020/hbase
drwxr-xr-x   - solr  supergroup          0 2015-11-03 11:15 hdfs://localhost:8020/solr
drwxrwxrwt   - hdfs  supergroup          0 2015-11-26 15:43 hdfs://localhost:8020/tmp
drwxr-xr-x   - hdfs  supergroup          0 2015-11-03 11:07 hdfs://localhost:8020/user
drwxr-xr-x   - hdfs  supergroup          0 2015-11-03 11:06 hdfs://localhost:8020/var
```

I started the container with: `sudo docker run -p 8020:8020 -p 50075:50075 -i -t -d caioquirino/docker-cloudera-quickstart`.  I thought 8020 was the port I needed to connect to since that's what's configured in `/etc/hadoop/conf/core-site.xml`, but I tried binding `-p 50075:50075` as you mentioned above for good measure.  I get different errors attempting to connect to either from my host system.  I'm trying to connect with the `hadoop-2.6.0` binary package downloaded from http://hadoop.apache.org/releases.html.

``` bash
foo@bar:~/hadoop-2.6.0/bin$ ./hdfs dfs -ls hdfs://127.0.0.1:50075/
ls: Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.; Host Details : local host is: "bar/127.0.1.1"; destination host is: "localhost":50075; 
foo@bar:~/hadoop-2.6.0/bin$ ./hdfs dfs -ls hdfs://127.0.0.1:8020/                                                                                              
ls: End of File Exception between local host is: "bar/127.0.1.1"; destination host is: "localhost":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException
```

Could this be auth related?  Network related?  I noticed when I `telnet localhost 8020` I connect and then immediately get disconnected.  Within the container I remain connected.

Any help would be appreciated.

**Comment by caioquirino** [comment]
@seglo Can you test with the docker container ip?
Maybe a listen problem.

Are you using boot2docker?
