### ISSUE TITLE
warning on hdfs commands

### ISSUE THREAD

**Issue by gliptak** [caioquirino/docker-cloudera-quickstart#4]
This is the output I get:

```
root@0c917496f229:/# hdfs dfs -ls /
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Found 5 items
drwxrwxrwx   - hdfs  supergroup          0 2015-01-15 09:18 /benchmarks
drwxr-xr-x   - hbase supergroup          0 2015-01-15 09:18 /hbase
drwxrwxrwt   - hdfs  supergroup          0 2015-01-15 09:17 /tmp
drwxr-xr-x   - hdfs  supergroup          0 2015-01-15 09:19 /user
drwxr-xr-x   - hdfs  supergroup          0 2015-01-15 09:17 /var
```

**Comment by caioquirino** [comment]
Hi Gliptak,

The problem is just a Java's SLF4J Logger that can't find any Logger Implementation. This warning doesn't affect on Hadoop.
When i run the following command, the error doesn't appear anymore:
export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:/usr/share/java/slf4j-simple.jar

I will fix this error as soon as i find the best place to add the class path entry.

Thank you!

**Comment by caioquirino** [comment]
@gliptak Warning fixed! :D 
Thank you for Collaboration!
